- name: MCM budget modifier
  hosts: localhost
  tasks:
    - name: get budget
      uri:
       url: "https://{{ url }}/rest/raid"
       method: GET
       body_format: json 
       headers:
        Content-Type: application/json
        x-apikey: "{{ apikey }}"
       body: '{"depermant":"{{ var_dep }}"}'
